"""Priya's Shop catalog seed data — run once (or anytime; it's idempotent,
matched by product name) against a live backend DB:

    backend/.venv/Scripts/python scripts/seed_catalog.py

Everything here is STATIC content written into the database at seed time
— not generated by an LLM at request time. Reviews are hand-written,
fixed strings; the only thing that varies per request is which products
a shopper happens to browse.

Phase 17 catalog rewrite: the original seed (Phase 9/10) shipped generic
electronics/footwear/fitness SKUs — including a real "Puma" branded item
— that had nothing to do with "Priya's Shop, handmade home decor." This
replaces the whole catalog with a small (~12 item) handmade-decor lineup
across Decor/Tableware/Textiles/Planters/Lighting.

Products 1 and 2 (and 3) predate this rewrite and have real orders/audit
history tied to their product_id, AND product 1's exact listed price
(₹2,499.00) and product 2's (₹299.00) are hardcoded in redteam's
tampering.py/concurrency.py (PRODUCT_ID_LISTED_PRICE_HUMAN/_AGENT) and
merchant_rules.py's PRODUCT_RULES[1] discount cap — so those three are
renamed IN PLACE via `match_name` (old name -> new decor identity) with
prices 1 and 2 left byte-for-byte unchanged, rather than deleted and
recreated, keeping every red-team price assumption and both products'
order history intact. Every other pre-existing SKU (the rest of the old
electronics/footwear/fitness/stationery set) is deleted at the end of
seed() since nothing outside this file depends on those rows.

Images: the generated SVG placeholder (small illustration made at seed
time from the product's own name + a category emoji, base64-encoded into
a data: URI — see _placeholder_svg below) was the original approach here,
specifically to avoid keyword-tagged stock photo mismatches (an earlier
version of this file hit real ones, including a real Nike logo on a
non-Nike product).

Phase 20: 11 of these 12 products were switched to a real downloaded
photo (frontend/public/images/products/*.jpg) instead, each one manually
vetted against its own listing text before being wired in — several
keyword-search candidates were rejected first (a mug with a printed
brand logo, a ritual brass vessel, a novelty animal-shaped planter stand,
a full dinner table with a wine decanter hiding the runner's actual
print, an antique brass ewer). "Brass Hand-Etched Planter Pot" never
found a clean match after five search rounds (~15 candidates, all either
ritual vessels, novelty shapes, or the wrong object entirely) and was
left on the original generated SVG rather than shipping a mismatch — so
this file, and this catalog, intentionally mixes both image sources. If
a future pass wants to replace that last one, re-run the same vetting
standard rather than taking the first keyword hit. (The table runner's
real photo is a floral tapestry pattern, not literally block-print, but
it's a genuine table runner shown in full use — the closest available
compromise after its own two failed rounds.)
"""

import base64
import sys
import textwrap
from pathlib import Path
from xml.sax.saxutils import escape as _xml_escape

sys.path.insert(0, str(Path(__file__).parent.parent))

from app.database import SessionLocal  # noqa: E402
from app.models.product import Product  # noqa: E402

# One consistent warm palette for every product image — matches the
# storefront's own design tokens (storefront-tokens.css) directly, rather
# than a different flat color swatch per item.
_BG_TOP = "#f2ede3"  # ivory
_BG_BOTTOM = "#e5dac9"  # putty-light
_RING = "#8b6552"  # clay
_INK = "#2b2823"  # ink


def _placeholder_svg(emoji: str, name: str, variant: int) -> str:
    # `variant` only nudges the stamp ring's rotation across a product's
    # own gallery images so thumbnails aren't pixel-identical — it never
    # changes the palette, so every product's images still read as the
    # same shop's shelf, not a different colored swatch per item.
    rotation = (variant - 1) * 11
    lines = textwrap.wrap(name, width=18)[:2]
    tspans = "".join(
        f'<tspan x="350" dy="{0 if i == 0 else 36}">{_xml_escape(line)}</tspan>' for i, line in enumerate(lines)
    )
    svg = (
        '<svg xmlns="http://www.w3.org/2000/svg" width="700" height="700">'
        "<defs><linearGradient id=\"bg\" x1=\"0\" y1=\"0\" x2=\"0\" y2=\"1\">"
        f'<stop offset="0" stop-color="{_BG_TOP}"/><stop offset="1" stop-color="{_BG_BOTTOM}"/>'
        "</linearGradient></defs>"
        f'<rect width="700" height="700" fill="url(#bg)"/>'
        f'<circle cx="350" cy="280" r="175" fill="none" stroke="{_RING}" stroke-width="2.5" '
        f'stroke-dasharray="3 11" transform="rotate({rotation} 350 280)"/>'
        f'<text x="350" y="290" font-size="150" text-anchor="middle" dominant-baseline="middle">{emoji}</text>'
        f'<text x="350" y="470" font-size="33" font-family="Georgia, \'Times New Roman\', serif" '
        f'font-weight="600" fill="{_INK}" text-anchor="middle">{tspans}</text>'
        "</svg>"
    )
    encoded = base64.b64encode(svg.encode("utf-8")).decode("ascii")
    return f"data:image/svg+xml;base64,{encoded}"


def placeholder_images(emoji: str, name: str, n: int = 2) -> list[str]:
    return [_placeholder_svg(emoji, name, i) for i in range(1, n + 1)]


PRODUCTS = [
    # --- renamed in place (price 1 & 2 unchanged — see module docstring) ----
    {
        "match_name": "Wireless Headphones",
        "name": "Hand-Painted Ceramic Table Vase",
        "price": 249900,
        "stock": 15,
        "description": "Tall stoneware vase, hand-painted glaze, one-of-a-kind",
        "category": "decor",
        "detail_description": (
            "A tall stoneware vase thrown and hand-painted in Priya's studio — no two are painted exactly "
            "alike, so the one you receive is genuinely one-of-a-kind. Glazed finish, food-safe if you'd "
            "like to use it for dried or fresh stems. Roughly 32cm tall."
        ),
        "image_urls": ["/images/products/ceramic-vase.jpg"],
        "rating": 4.4,
        "review_count": 312,
        "negotiable": True,
        "reviews": [
            {"author": "Ananya R.", "rating": 5, "text": "The glaze pattern on mine is gorgeous — genuinely looks like a piece from a boutique, not a mass shop."},
            {"author": "Vikram S.", "rating": 4, "text": "Beautiful vase, slightly heavier than I expected but that's fine for stability with tall stems."},
            {"author": "Priya M.", "rating": 4, "text": "Arrived carefully wrapped, no chips. The hand-painted detailing is even nicer in person."},
            {"author": "Rohit K.", "rating": 5, "text": "Bought this after my old vase broke — the craftsmanship here is on another level."},
        ],
    },
    {
        "match_name": "Ceramic Coffee Mug",
        "name": "Hand-Thrown Stoneware Mug",
        "price": 29900,
        "stock": 50,
        "description": "350ml hand-thrown mug, reactive glaze, dishwasher safe",
        "category": "tableware",
        "detail_description": (
            "A sturdy 350ml stoneware mug, hand-thrown on the wheel with a reactive glaze finish so the "
            "color shifts subtly across the surface. Comfortable handle, microwave and dishwasher safe. "
            "Sold individually — mix and match glazes for a set that doesn't look mass-produced."
        ),
        "image_urls": ["/images/products/stoneware-mug.jpg"],
        "rating": 4.6,
        "review_count": 98,
        "negotiable": True,
        "reviews": [
            {"author": "Meera J.", "rating": 5, "text": "Perfect weight in hand, and the glaze really does look a little different every time the light changes."},
            {"author": "Arjun T.", "rating": 4, "text": "Lovely mug, handle could be a touch bigger for people with larger hands."},
            {"author": "Sana P.", "rating": 5, "text": "Ordered four in different glazes for the kitchen — no two look identical, which is exactly the appeal."},
        ],
    },
    {
        "match_name": "Puma Running Shoes - Black/White",
        "name": "Handwoven Jute Storage Basket - Large",
        "price": 189900,
        "stock": 25,
        "description": "Large handwoven jute basket with handles, natural fiber",
        "category": "decor",
        "detail_description": (
            "A large storage basket handwoven from natural jute fiber, with sturdy handles on both sides. "
            "Roomy enough for throws, toys, or plant pots — doubles as floor decor even when empty. "
            "Roughly 40cm diameter x 35cm tall."
        ),
        "image_urls": ["/images/products/jute-basket.jpg"],
        "rating": 4.3,
        "review_count": 187,
        "negotiable": True,
        "reviews": [
            {"author": "Karan V.", "rating": 4, "text": "Great size for the living room, and it looks intentional even half-empty."},
            {"author": "Divya N.", "rating": 5, "text": "The weave quality is excellent — sturdy enough to hold a stack of blankets without sagging."},
            {"author": "Farhan A.", "rating": 4, "text": "Slight jute smell on arrival that faded after a couple of days outside."},
        ],
    },
    # --- textiles -------------------------------------------------------------
    {
        "name": "Macrame Wall Hanging - Boho Diamond",
        "price": 149900,
        "stock": 22,
        "description": "Hand-knotted cotton macrame, wooden dowel included",
        "category": "textiles",
        "detail_description": (
            "A hand-knotted macrame wall hanging in a diamond lattice pattern, made from natural cotton "
            "cord on a wooden dowel — ready to hang straight out of the box. Roughly 60cm wide x 90cm long."
        ),
        "image_urls": ["/images/products/macrame.jpg"],
        "rating": 4.7,
        "review_count": 96,
        "negotiable": True,
        "reviews": [
            {"author": "Ishaan G.", "rating": 5, "text": "Way more detailed in person than the photos suggested. Instant focal point in the room."},
            {"author": "Riya D.", "rating": 4, "text": "Beautiful knotting work, took a day for the cord to relax into its final shape after unpacking."},
            {"author": "Amit B.", "rating": 5, "text": "Exactly the boho look I wanted for the reading corner."},
        ],
    },
    {
        "name": "Embroidered Cushion Cover - Kantha Stitch",
        "price": 89900,
        "stock": 40,
        "description": "16x16in cotton cover, hand kantha embroidery",
        "category": "textiles",
        "detail_description": (
            "A 16x16in cotton cushion cover finished with traditional hand kantha running-stitch "
            "embroidery. Hidden zip closure, machine washable on gentle cycle. Insert sold separately."
        ),
        "image_urls": ["/images/products/cushion.jpg"],
        "rating": 4.5,
        "review_count": 141,
        "negotiable": True,
        "reviews": [
            {"author": "Nikhil R.", "rating": 5, "text": "The stitching detail is stunning for the price — looks handmade because it is."},
            {"author": "Tanvi S.", "rating": 4, "text": "Lovely cover, colors are slightly warmer in person than on screen, in a good way."},
        ],
    },
    {
        "name": "Block-Print Table Runner",
        "price": 69900,
        "stock": 35,
        "description": "Cotton table runner, hand block-printed, 13x72in",
        "category": "textiles",
        "detail_description": (
            "A cotton table runner hand block-printed with a traditional floral motif, 13in x 72in. "
            "Pre-washed to reduce shrinkage; a gentle iron brings the print back to crisp after washing."
        ),
        "image_urls": ["/images/products/table-runner.jpg"],
        "rating": 4.4,
        "review_count": 58,
        "negotiable": False,
        "reviews": [
            {"author": "Yusuf K.", "rating": 4, "text": "Print quality is even across the whole length, no faded patches."},
            {"author": "Pooja L.", "rating": 5, "text": "Dresses up the dining table instantly. Held its color through the first wash."},
        ],
    },
    # --- planters ---------------------------------------------------------------
    {
        "name": "Terracotta Planter with Saucer - Medium",
        "price": 64900,
        "stock": 55,
        "description": "Hand-thrown terracotta pot, 8in, drainage + saucer",
        "category": "planters",
        "detail_description": (
            "A hand-thrown terracotta planter, 8in diameter, with a drainage hole and matching saucer "
            "included. Unglazed exterior lets the clay breathe, which most houseplants prefer."
        ),
        "image_urls": ["/images/products/terracotta-planter.jpg"],
        "rating": 4.5,
        "review_count": 203,
        "negotiable": True,
        "reviews": [
            {"author": "Neha C.", "rating": 5, "text": "My monstera is thriving in this — drainage hole actually works, unlike some decorative pots."},
            {"author": "Suresh P.", "rating": 4, "text": "Good size and weight, saucer fits snugly underneath."},
            {"author": "Kavya M.", "rating": 5, "text": "Rustic look, exactly matches the other terracotta pieces in my hallway."},
        ],
    },
    {
        "name": "Brass Hand-Etched Planter Pot - Small",
        "price": 54900,
        "stock": 30,
        "description": "Small brass pot, hand-etched floral pattern, indoor use",
        "category": "planters",
        "detail_description": (
            "A small brass planter pot with a hand-etched floral pattern around the rim — best paired with "
            "a plastic nursery pot inside, since brass isn't food/plant-safe on direct contact long-term. "
            "Roughly 5in diameter, indoor use."
        ),
        "image_urls": placeholder_images("🪴", "Brass Hand-Etched Planter Pot", 2),
        "rating": 4.2,
        "review_count": 67,
        "negotiable": False,
        "reviews": [
            {"author": "Devansh J.", "rating": 4, "text": "Etching detail is lovely, tarnishes a little over time which just adds to the character."},
            {"author": "Ritika A.", "rating": 4, "text": "Small but well made. Using it for a succulent with the nursery pot tucked inside."},
        ],
    },
    # --- tableware ----------------------------------------------------------------
    {
        "name": "Wooden Coasters Set (4-pack) - Mango Wood",
        "price": 79900,
        "stock": 45,
        "description": "Live-edge mango wood coasters, set of 4",
        "category": "tableware",
        "detail_description": (
            "A set of 4 live-edge mango wood coasters, each with a slightly different grain since the wood "
            "is never cut from the same section twice. Finished with a food-safe oil, wipes clean easily."
        ),
        "image_urls": ["/images/products/wooden-coasters.jpg"],
        "rating": 4.4,
        "review_count": 112,
        "negotiable": True,
        "reviews": [
            {"author": "Gauri P.", "rating": 5, "text": "Each coaster genuinely has its own grain pattern — nice touch that they're not identical."},
            {"author": "Vivek S.", "rating": 4, "text": "Sturdy, good weight, protects the table well from condensation."},
        ],
    },
    {
        "name": "Hand-Painted Wooden Serving Tray",
        "price": 129900,
        "stock": 20,
        "description": "Mango wood tray, hand-painted rim, with handles",
        "category": "tableware",
        "detail_description": (
            "A mango wood serving tray with a hand-painted decorative rim and cut-out handles for easy "
            "carrying. Great for breakfast in bed, chai service, or as a styled coffee-table catch-all. "
            "Roughly 40cm x 28cm."
        ),
        "image_urls": ["/images/products/wooden-tray.jpg"],
        "rating": 4.7,
        "review_count": 84,
        "negotiable": True,
        "reviews": [
            {"author": "Ishita V.", "rating": 5, "text": "Gave this as a housewarming gift and the recipient wouldn't stop talking about the painted rim."},
            {"author": "Ankit R.", "rating": 5, "text": "Sturdy enough for actual daily use, not just decorative — exactly what I wanted."},
            {"author": "Nandini K.", "rating": 4, "text": "Beautiful tray, hand-wash only which I didn't realize until I read the care card, but worth it."},
        ],
    },
    # --- decor / lighting -----------------------------------------------------------
    {
        "name": "Hand-Poured Soy Candle - Sandalwood",
        "price": 49900,
        "stock": 60,
        "description": "Hand-poured soy wax candle, sandalwood, 40hr burn",
        "category": "decor",
        "detail_description": (
            "A hand-poured soy wax candle in a reusable ceramic vessel, scented with sandalwood. Cotton "
            "wick, roughly 40 hours of burn time. Once finished, the vessel makes a nice small planter."
        ),
        "image_urls": ["/images/products/soy-candle.jpg"],
        "rating": 4.6,
        "review_count": 154,
        "negotiable": True,
        "reviews": [
            {"author": "Chirag D.", "rating": 5, "text": "Scent is warm without being overpowering, fills a medium room nicely."},
            {"author": "Payal M.", "rating": 4, "text": "Burns evenly, no tunneling. Keeping the vessel for a succulent once it's done."},
        ],
    },
    {
        "name": "Rattan Pendant Lamp Shade",
        "price": 219900,
        "stock": 18,
        "description": "Handwoven rattan pendant shade, fitting not included",
        "category": "lighting",
        "detail_description": (
            "A handwoven rattan pendant lamp shade that casts a warm, dappled light pattern. Fits standard "
            "E27 pendant fittings (fitting/cord sold separately). Roughly 35cm diameter."
        ),
        "image_urls": ["/images/products/rattan-lamp.jpg"],
        "rating": 4.3,
        "review_count": 71,
        "negotiable": False,
        "reviews": [
            {"author": "Sneha B.", "rating": 5, "text": "The light pattern this casts on the ceiling is beautiful, exactly what I hoped for."},
            {"author": "Rahul G.", "rating": 4, "text": "Well woven, lightweight. Wish it came with the fitting included but easy enough to source separately."},
            {"author": "Aditi J.", "rating": 4, "text": "Looks like a much pricier piece — great addition to the living room."},
        ],
    },
]


def seed():
    db = SessionLocal()
    created, updated, removed = 0, 0, 0
    try:
        touched_ids = set()
        for raw in PRODUCTS:
            data = dict(raw)
            old_name = data.pop("match_name", None)
            # Bug fixed Phase 20: a match_name lookup only ever finds the
            # OLD name, so a second run (after the first already renamed
            # the row) found nothing, created a duplicate with a fresh ID,
            # and deleted the real row — silently orphaning every order's
            # product_id FK. Falling back to the current `name` makes the
            # match_name lookup idempotent across repeat runs.
            existing = None
            if old_name:
                existing = db.query(Product).filter(Product.name == old_name).first()
            if existing is None:
                existing = db.query(Product).filter(Product.name == data["name"]).first()
            if existing:
                for key, value in data.items():
                    setattr(existing, key, value)
                db.flush()
                touched_ids.add(existing.id)
                updated += 1
            else:
                obj = Product(**data)
                db.add(obj)
                db.flush()
                touched_ids.add(obj.id)
                created += 1

        # Anything left over is a pre-Phase-17 SKU (the old electronics/
        # footwear/fitness/stationery catalog) that isn't part of Priya's
        # Shop's handmade-decor lineup — remove it so the storefront and
        # admin catalog only ever show real decor items.
        stale = db.query(Product).filter(~Product.id.in_(touched_ids)).all()
        for p in stale:
            db.delete(p)
            removed += 1

        db.commit()
    finally:
        db.close()
    print(f"Seed complete: {created} created, {updated} updated, {removed} removed, {len(PRODUCTS)} total.")


if __name__ == "__main__":
    seed()
